spring:
  cache:
    caffeine:
      spec: expireAfterWrite=1m
  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DATABASE_PORT:3307}/twitch?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: "classpath:database-init.sql"
  jackson:
    default-property-inclusion: non_null
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: twitch

      client:
        config:
          twitch-api:
            url: https://api.twitch.tv/helix
            loggerLevel: basic
            default-request-headers:
              Client-Id: "3v4g5u8sxlmyaqlugjcjlhtkfwrcoz"
  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id: "3v4g5u8sxlmyaqlugjcjlhtkfwrcoz"
            client-secret: "z1xhmrx01jwajuboov9p388xb6jgv5"
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token

server:
  port: 8080
logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG
    com.laioffer.twitch.external.TwitchApiClient: DEBUG # Outgoing HTTP requests
    org.springframework.jdbc.core: DEBUG # SQL



